// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, type, currency, initial_balance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, currency, initial_balance, created_at, updated_at
`

type CreateAccountParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	Name           string         `json:"name"`
	Type           string         `json:"type"`
	Currency       string         `json:"currency"`
	InitialBalance pgtype.Numeric `json:"initial_balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.InitialBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.UserID)
	return err
}

const deleteAllUserAccounts = `-- name: DeleteAllUserAccounts :exec
DELETE FROM accounts WHERE user_id = $1
`

func (q *Queries) DeleteAllUserAccounts(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserAccounts, userID)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, type, currency, initial_balance, created_at, updated_at FROM accounts WHERE id = $1 AND user_id = $2
`

type GetAccountParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, user_id, name, type, currency, initial_balance, created_at, updated_at FROM accounts WHERE user_id = $1 AND name = $2
`

type GetAccountByNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) GetAccountByName(ctx context.Context, arg GetAccountByNameParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByName, arg.UserID, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountTransactionSums = `-- name: GetAccountTransactionSums :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::DECIMAL(15,2) AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::DECIMAL(15,2) AS total_expense
FROM transactions
WHERE account_id = $1
`

type GetAccountTransactionSumsRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
}

func (q *Queries) GetAccountTransactionSums(ctx context.Context, accountID uuid.UUID) (GetAccountTransactionSumsRow, error) {
	row := q.db.QueryRow(ctx, getAccountTransactionSums, accountID)
	var i GetAccountTransactionSumsRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.user_id, a.name, a.type, a.currency, a.initial_balance, a.created_at, a.updated_at,
  COALESCE(COUNT(t.id), 0)::INTEGER AS recent_tx_count
FROM accounts a
LEFT JOIN transactions t
  ON t.account_id = a.id
  AND t.type = 'expense'
  AND t.transfer_id IS NULL
  AND t.date >= CURRENT_DATE - INTERVAL '30 days'
WHERE a.user_id = $1
GROUP BY a.id
ORDER BY name
`

type ListAccountsRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Currency       string             `json:"currency"`
	InitialBalance pgtype.Numeric     `json:"initial_balance"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RecentTxCount  int32              `json:"recent_tx_count"`
}

func (q *Queries) ListAccounts(ctx context.Context, userID uuid.UUID) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.InitialBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecentTxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, type = $3, initial_balance = $4, updated_at = now()
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, name, type, currency, initial_balance, created_at, updated_at
`

type UpdateAccountParams struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	Type           string         `json:"type"`
	InitialBalance pgtype.Numeric `json:"initial_balance"`
	UserID         uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.InitialBalance,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.InitialBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
