// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, parent_id, name, type)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, parent_id, name, type, created_at
`

type CreateCategoryParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createDefaultCategories = `-- name: CreateDefaultCategories :exec
INSERT INTO categories (user_id, name, type) VALUES
    ($1, 'Salary', 'income'),
    ($1, 'Other Income', 'income'),
    ($1, 'Food', 'expense'),
    ($1, 'Transport', 'expense'),
    ($1, 'Other Expense', 'expense')
`

func (q *Queries) CreateDefaultCategories(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createDefaultCategories, userID)
	return err
}

const deleteAllUserCategories = `-- name: DeleteAllUserCategories :exec
DELETE FROM categories WHERE user_id = $1
`

func (q *Queries) DeleteAllUserCategories(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserCategories, userID)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, parent_id, name, type, created_at FROM categories WHERE id = $1 AND user_id = $2
`

type GetCategoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByNameAndType = `-- name: GetCategoryByNameAndType :one
SELECT id, user_id, parent_id, name, type, created_at FROM categories WHERE user_id = $1 AND name = $2 AND type = $3 AND parent_id IS NULL
`

type GetCategoryByNameAndTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Type   string    `json:"type"`
}

func (q *Queries) GetCategoryByNameAndType(ctx context.Context, arg GetCategoryByNameAndTypeParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByNameAndType, arg.UserID, arg.Name, arg.Type)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const getSubcategoryByNameAndType = `-- name: GetSubcategoryByNameAndType :one
SELECT id, user_id, parent_id, name, type, created_at FROM categories WHERE user_id = $1 AND name = $2 AND type = $3 AND parent_id = $4
`

type GetSubcategoryByNameAndTypeParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetSubcategoryByNameAndType(ctx context.Context, arg GetSubcategoryByNameAndTypeParams) (Category, error) {
	row := q.db.QueryRow(ctx, getSubcategoryByNameAndType,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.ParentID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const hasCategoryTransactions = `-- name: HasCategoryTransactions :one
SELECT EXISTS(SELECT 1 FROM transactions WHERE category_id = $1) AS has_transactions
`

func (q *Queries) HasCategoryTransactions(ctx context.Context, categoryID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasCategoryTransactions, categoryID)
	var has_transactions bool
	err := row.Scan(&has_transactions)
	return has_transactions, err
}

const hasChildCategories = `-- name: HasChildCategories :one
SELECT EXISTS(SELECT 1 FROM categories WHERE parent_id = $1) AS has_children
`

func (q *Queries) HasChildCategories(ctx context.Context, parentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasChildCategories, parentID)
	var has_children bool
	err := row.Scan(&has_children)
	return has_children, err
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.user_id, c.parent_id, c.name, c.type, c.created_at,
  COALESCE(COUNT(t.id), 0)::INTEGER AS recent_tx_count
FROM categories c
LEFT JOIN transactions t
  ON t.category_id = c.id
  AND t.type = 'expense'
  AND t.transfer_id IS NULL
  AND t.date >= CURRENT_DATE - INTERVAL '30 days'
WHERE c.user_id = $1
GROUP BY c.id
ORDER BY c.type, c.name
`

type ListCategoriesRow struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	ParentID      pgtype.UUID        `json:"parent_id"`
	Name          string             `json:"name"`
	Type          string             `json:"type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RecentTxCount int32              `json:"recent_tx_count"`
}

func (q *Queries) ListCategories(ctx context.Context, userID uuid.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.RecentTxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, parent_id = $3
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, parent_id, name, type, created_at
`

type UpdateCategoryParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
	UserID   uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
