// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForBulkCreateTransactions implements pgx.CopyFromSource.
type iteratorForBulkCreateTransactions struct {
	rows                 []BulkCreateTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].AccountID,
		r.rows[0].CategoryID,
		r.rows[0].Type,
		r.rows[0].Amount,
		r.rows[0].Description,
		r.rows[0].Date,
	}, nil
}

func (r iteratorForBulkCreateTransactions) Err() error {
	return nil
}

func (q *Queries) BulkCreateTransactions(ctx context.Context, arg []BulkCreateTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"user_id", "account_id", "category_id", "type", "amount", "description", "date"}, &iteratorForBulkCreateTransactions{rows: arg})
}
