// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exchange_rates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestRate = `-- name: GetLatestRate :one
SELECT id, from_currency, to_currency, rate, date FROM exchange_rates
WHERE from_currency = $1 AND to_currency = $2
ORDER BY date DESC
LIMIT 1
`

type GetLatestRateParams struct {
	FromCurrency string `json:"from_currency"`
	ToCurrency   string `json:"to_currency"`
}

func (q *Queries) GetLatestRate(ctx context.Context, arg GetLatestRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getLatestRate, arg.FromCurrency, arg.ToCurrency)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.Date,
	)
	return i, err
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT id, from_currency, to_currency, rate, date FROM exchange_rates ORDER BY date DESC, from_currency, to_currency
`

func (q *Queries) ListExchangeRates(ctx context.Context) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.Rate,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :one
INSERT INTO exchange_rates (from_currency, to_currency, rate, date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (from_currency, to_currency, date)
DO UPDATE SET rate = EXCLUDED.rate
RETURNING id, from_currency, to_currency, rate, date
`

type UpsertExchangeRateParams struct {
	FromCurrency string         `json:"from_currency"`
	ToCurrency   string         `json:"to_currency"`
	Rate         pgtype.Numeric `json:"rate"`
	Date         pgtype.Date    `json:"date"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, upsertExchangeRate,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.Rate,
		arg.Date,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.Date,
	)
	return i, err
}
