// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: export.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const exportTransactions = `-- name: ExportTransactions :many
SELECT
    t.date,
    a.name AS account_name,
    COALESCE(pc.name, '') AS parent_category_name,
    COALESCE(c.name, '') AS category_name,
    t.type,
    t.amount,
    a.currency,
    t.description,
    t.transfer_id,
    COALESCE(ta.name, '') AS transfer_account_name
FROM transactions t
JOIN accounts a ON t.account_id = a.id
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN categories pc ON c.parent_id = pc.id
LEFT JOIN transactions t2
    ON t.transfer_id = t2.transfer_id
    AND t2.id != t.id
    AND t.transfer_id IS NOT NULL
LEFT JOIN accounts ta ON t2.account_id = ta.id
WHERE t.user_id = $1
    AND t.date >= $2
    AND t.date <= $3
ORDER BY t.date, t.created_at
`

type ExportTransactionsParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type ExportTransactionsRow struct {
	Date                pgtype.Date    `json:"date"`
	AccountName         string         `json:"account_name"`
	ParentCategoryName  string         `json:"parent_category_name"`
	CategoryName        string         `json:"category_name"`
	Type                string         `json:"type"`
	Amount              pgtype.Numeric `json:"amount"`
	Currency            string         `json:"currency"`
	Description         string         `json:"description"`
	TransferID          pgtype.UUID    `json:"transfer_id"`
	TransferAccountName string         `json:"transfer_account_name"`
}

func (q *Queries) ExportTransactions(ctx context.Context, arg ExportTransactionsParams) ([]ExportTransactionsRow, error) {
	rows, err := q.db.Query(ctx, exportTransactions, arg.UserID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportTransactionsRow{}
	for rows.Next() {
		var i ExportTransactionsRow
		if err := rows.Scan(
			&i.Date,
			&i.AccountName,
			&i.ParentCategoryName,
			&i.CategoryName,
			&i.Type,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.TransferID,
			&i.TransferAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
