// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Currency       string             `json:"currency"`
	InitialBalance pgtype.Numeric     `json:"initial_balance"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Currency struct {
	Code   string `json:"code"`
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
}

type ExchangeRate struct {
	ID           uuid.UUID      `json:"id"`
	FromCurrency string         `json:"from_currency"`
	ToCurrency   string         `json:"to_currency"`
	Rate         pgtype.Numeric `json:"rate"`
	Date         pgtype.Date    `json:"date"`
}

type Transaction struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	AccountID    uuid.UUID          `json:"account_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Type         string             `json:"type"`
	Amount       pgtype.Numeric     `json:"amount"`
	Description  string             `json:"description"`
	Date         pgtype.Date        `json:"date"`
	TransferID   pgtype.UUID        `json:"transfer_id"`
	ExchangeRate pgtype.Numeric     `json:"exchange_rate"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	BaseCurrency string             `json:"base_currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	InviteCode   pgtype.Text        `json:"invite_code"`
}
