// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, display_name, base_currency, invite_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, display_name, base_currency, created_at, updated_at, invite_code
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
	BaseCurrency string      `json:"base_currency"`
	InviteCode   pgtype.Text `json:"invite_code"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.BaseCurrency,
		arg.InviteCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, base_currency, created_at, updated_at, invite_code FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, base_currency, created_at, updated_at, invite_code FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = $2, base_currency = $3, updated_at = now()
WHERE id = $1
RETURNING id, username, password_hash, display_name, base_currency, created_at, updated_at, invite_code
`

type UpdateUserParams struct {
	ID           uuid.UUID `json:"id"`
	DisplayName  string    `json:"display_name"`
	BaseCurrency string    `json:"base_currency"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.DisplayName, arg.BaseCurrency)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.BaseCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}
