package handler

// commonPasswords lists frequently breached / guessable passwords that must be
// rejected at registration and on password change. The list is intentionally
// small — it's a floor, not a comprehensive breach check. Sourced from the
// top of SecLists' common credential lists, filtered to entries of length >= 10
// (shorter passwords are already rejected by the length validator).
var commonPasswords = map[string]struct{}{
	"password":         {},
	"password1":        {},
	"password12":       {},
	"password123":      {},
	"password1234":     {},
	"password12345":    {},
	"password123456":   {},
	"passw0rd":         {},
	"passw0rd1":        {},
	"p@ssw0rd":         {},
	"p@ssword1":        {},
	"p@ssword123":      {},
	"qwerty12345":      {},
	"qwerty123456":     {},
	"1234567890":       {},
	"12345678901":      {},
	"123456789012":     {},
	"1234567890123":    {},
	"12345qwerty":      {},
	"qwertyuiop":       {},
	"qwertyui12":       {},
	"iloveyou1":        {},
	"iloveyou12":       {},
	"iloveyou123":      {},
	"welcome123":       {},
	"welcome1234":      {},
	"welcome12345":     {},
	"letmein123":       {},
	"letmein1234":      {},
	"admin12345":       {},
	"admin123456":      {},
	"administrator":    {},
	"administrator1":   {},
	"changeme123":      {},
	"changeme1234":     {},
	"default1234":      {},
	"football1":        {},
	"football12":       {},
	"baseball12":       {},
	"basketball1":      {},
	"superman123":      {},
	"batman1234":       {},
	"pokemon123":       {},
	"dragon1234":       {},
	"master1234":       {},
	"monkey1234":       {},
	"shadow1234":       {},
	"michael123":       {},
	"michael1234":      {},
	"jennifer1":        {},
	"jennifer12":       {},
	"sunshine1":        {},
	"sunshine12":       {},
	"princess1":        {},
	"princess12":       {},
	"whatever1":        {},
	"whatever12":       {},
	"trustno1234":      {},
	"starwars12":       {},
	"computer123":      {},
	"internet123":      {},
	"secret1234":       {},
	"secret12345":      {},
	"abc1234567":       {},
	"abcdefghij":       {},
	"qwerty1234":       {},
	"zxcvbnm123":       {},
	"asdfghjkl1":       {},
	"asdfghjkl12":      {},
	"1qaz2wsx3edc":     {},
	"1q2w3e4r5t":       {},
	"1q2w3e4r5t6y":     {},
	"qazwsxedc1":       {},
	"qazwsxedcrfv":     {},
	"thisisapassword":  {},
	"letmeinplease":    {},
	"iloveyouforever":  {},
	"thebestpassword":  {},
	"passwordpassword": {},
}

func isCommonPassword(s string) bool {
	_, ok := commonPasswords[s]
	return ok
}
